-- Crear la base de datos
CREATE USER growby IDENTIFIED BY Growby@2024;
GRANT ALL PRIVILEGES TO growby;

-- Tabla para Clientes
CREATE TABLE clientes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    telefono VARCHAR2(20)
);

-- Tabla para Productos
CREATE TABLE productos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL,
    descripcion VARCHAR2(500),
    precio NUMBER(10, 2) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR2(10) CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- Tabla para Órdenes
CREATE TABLE ordenes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad NUMBER NOT NULL,
    total NUMBER(10, 2) NOT NULL,
    fecha_orden TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    cliente_id NUMBER NOT NULL,
    producto_id NUMBER NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    FOREIGN KEY (producto_id) REFERENCES productos(id)
);


-- Insertar clientes
INSERT INTO clientes (nombre, email, telefono) VALUES ('Juan Pérez', 'juan.perez@example.com', '555-1234');
INSERT INTO clientes (nombre, email, telefono) VALUES ('María López', 'maria.lopez@example.com', '555-5678');
INSERT INTO clientes (nombre, email, telefono) VALUES ('Carlos García', 'carlos.garcia@example.com', '555-8765');

-- Insertar productos
INSERT INTO productos (nombre, descripcion, precio, estado) VALUES ('Producto A', 'Descripción del Producto A', 10.00, 'ACTIVO');
INSERT INTO productos (nombre, descripcion, precio, estado) VALUES ('Producto B', 'Descripción del Producto B', 15.50, 'ACTIVO');
INSERT INTO productos (nombre, descripcion, precio, estado) VALUES ('Producto C', 'Descripción del Producto C', 8.75, 'INACTIVO');

-- Insertar ordenes
INSERT INTO ordenes (cantidad, total, fecha_orden, cliente_id, producto_id) VALUES (2, 20.00, CURRENT_TIMESTAMP, 1, 1);
INSERT INTO ordenes (cantidad, total, fecha_orden, cliente_id, producto_id) VALUES (1, 15.50, CURRENT_TIMESTAMP, 2, 2);
INSERT INTO ordenes (cantidad, total, fecha_orden, cliente_id, producto_id) VALUES (3, 26.25, CURRENT_TIMESTAMP, 3, 1);

